name: Daily Dagster Pipelines

on:
  schedule:
    - cron: "25 14 * * *" # glucose_ingest_job -> 14:25 UTC
    - cron: "30 14 * * *" # partitioned_dbt_job -> 14:30 UTC
    - cron: "35 14 * * *" # export_job -> 14:35 UTC
  workflow_dispatch:

jobs:
  glucose_ingest_job:
    runs-on: ubuntu-latest
    if: github.event.schedule == '25 14 * * *' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run glucose_ingest_job
        run: |
          dagster job execute -f dexcom_dagster/jobs/glucose_ingest_job.py

  partitioned_dbt_job:
    runs-on: ubuntu-latest
    if: github.event.schedule == '30 14 * * *' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run partitioned_dbt_job
        run: |
          dagster job execute -f dexcom_dagster/jobs/dbt_pipeline_job.py

  export_job:
    runs-on: ubuntu-latest
    if: github.event.schedule == '35 14 * * *' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run export_job
        run: |
          dagster job execute -f dexcom_dagster/jobs/export_job.py
