version: 2

models:
  - name: int_glucose_readings_combined
    description: "Unified glucose readings from PyDexcom API and T:Connect CSV export. Readings expected every 5 minutes where data is available. When data is unavailable, gaps or null values may be present."
    columns:
      - name: reading_timestamp
        description: "Timestamp of glucose reading in Central timezone (accounts for daylight saving time)"
        tests:
          - not_null
          - unique

      - name: glucose_mg_dl
        description: "Glucose value in mg/dL"
        tests:
          - not_null
      - name: day_of_week
        description: "Day of the week (0=Monday, 6=Sunday)"
      - name: day_name
        description: "Name of the day (e.g., Monday, Tuesday)"
      - name: iso_week
        description: "ISO week number of the year (1-53)"
      - name: iso_year
      - name: month
        description: "Month of the year (1-12)"
      - name: year
        description: "Year of the reading"
      - name: month_start_date
        description: "Start date of the month (YYYY-MM-DD)"
      - name: hour_of_day
        description: "Hour of the day (0-23)"
      - name: time_of_day_bucket
        description: "Morning 5am-11am, Afternoon 12pm-5pm, Evening 5pm-9pm, Night 9pm-5am"

  - name: int_glucose_readings_backfill
    description: "Backfilled glucose readings from T:Connect CSV export. Readings expected every 5 minutes where data is available. When data is unavailable, gaps or null values may be present."
    config:
      enabled: false
    columns:
      - name: reading_timestamp
        description: "Timestamp of glucose reading in Central timezone (accounts for daylight saving time)"
        tests:
          - not_null
          - unique

      - name: glucose_mg_dl
        description: "Glucose value in mg/dL"
        tests:
          - not_null

      - name: day_of_week
        description: "Day of the week (0=Sunday, 6=Saturday)"

      - name: day_name
        description: "Full name of the day (e.g., Monday, Tuesday)"

      - name: iso_week
        description: "ISO week number of the year (00:53)"

      - name: iso_year
        description: "ISO 8601-compliant year associated with the iso_week"

      - name: month
        description: "Month of the year (1:12)"

      - name: year
        description: "Calendar year (e.g., 2025)"

      - name: month_start_date
        description: "First date of the calendar month (YYYY-MM-DD)"

      - name: hour_of_day
        description: "Hour of the day the reading occurred (0:23)"

      - name: time_of_day_bucket
        description: "Time bucket for the reading: Morning (5:11), Afternoon (12:16), Evening (17:20), Night (21:4)"
