version: 2

sources:
  - name: dexcom
    schema: main
    tables:
      - name: dexcom_glucose_readings
        external:
          location: "s3://chumbucket4356/dexcom/*/"
          file_format: parquet
        description: "Glucose readings ingested via PyDexcom API."
        loaded_at_field: reading_ts
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 72
            period: hour
        columns:
          - name: reading_ts
            description: "Timestamp of glucose reading in Central timezone"
            tests:
              - not_null
          - name: glucose_mg_dl
            description: "Glucose value in mg/dL"
            tests:
              - not_null

  - name: t_connect
    schema: main
    tables:
      - name: t_connect_glucose_readings
        external:
          location: "s3://chumbucket4356/t_connect/*.parquet"
          file_format: parquet
        description: "Backfilled glucose data from t:connect export."
        columns:
          - name: reading_timestamp
            description: "Timestamp of glucose reading in Central timezone"
            tests:
              - not_null
          - name: glucose_mg_dl
            description: "Glucose value in mg/dL"
            tests:
              - not_null
