version: 2

sources:
  - name: dexcom
    schema: main
    tables:
      - name: dexcom_glucose_readings
        identifier: stg_pydex_readings
        description: "Glucose readings ingested via PyDexcom API."
        loaded_at_field: reading_ts
        freshness:
          warn_after:
            count: 2
            period: hour
          error_after:
            count: 6
            period: hour
        columns:
          - name: reading_ts
            description: "Timestamp of glucose reading in UTC timezone"
            tests:
              - not_null
          - name: glucose_mg_dl
            description: "Glucose value in mg/dL"
            tests:
              - not_null

  - name: t_connect
    schema: main
    tables:
      - name: t_connect_glucose_readings
        identifier: stg_tconnect_csv_data
        description: "Backfilled glucose data from t:connect export."
        columns:
          - name: reading_ts
            description: "Timestamp of glucose reading in Central timezone"
            tests:
              - not_null
          - name: glucose_mg_dl
            description: "Glucose value in mg/dL"
            tests:
              - not_null
